### ISSUE TITLE
wurstmeister/zookeeper is severely outdated

### ISSUE THREAD

**Issue by AgentOak** [ExplorViz/docker-configuration#3]
The wurstmeister/zookeeper image we are using hasn't been updated in [12 months](https://hub.docker.com/r/wurstmeister/zookeeper) and still uses Java 7 and Ubuntu 14.04, whose extended support ran out last April.
It is also very inefficient, e.g. keeping archive files in the image after they have been extracted.

There is now an [official zookeeper image](https://hub.docker.com/_/zookeeper) on dockerhub based on Debian and OpenJDK 8 that is actively maintained and much lighter:
```
wurstmeister/zookeeper    latest     3f43f72cb283      12 months ago       510MB
zookeeper                 latest     605e906e9bab      4 days ago          224MB
```

Maybe it also improves the slow shutdown times we're seeing with zookeeper right now.

**Comment by Alexander-Krause-Glau** [comment]
Done in #4
